// This file was generated by Prisma, and assumes you have installed the following:
// npm install --save-dev prisma dotenv
import { config as dotenvConfig } from "dotenv";
import { defineConfig } from "prisma/config";

function rootRelative(path: string): string {
  return new URL(`../../${path}`, import.meta.url).pathname;
}

// Same load order and precedence as the pre-monorepo setup.
dotenvConfig({ path: rootRelative(".env") });
dotenvConfig({ path: rootRelative(".env.local") });

export default defineConfig({
  schema: "prisma/",
  migrations: {
    path: "prisma/migrations",
  },
  datasource: {
    url: process.env["DATABASE_URL"],
    shadowDatabaseUrl: process.env["SHADOW_DATABASE_URL"],
  },
});
