// This file was generated by Prisma, and assumes you have installed the following:
// npm install --save-dev prisma dotenv
import { config as dotenvDefault } from "dotenv";
import { config as dotenvLocal } from "dotenv";
import { defineConfig } from "prisma/config";

function rootRelative(path: string): string {
  return new URL(`../../${path}`, import.meta.url).pathname;
}

// Same load order and precedence as the pre-monorepo setup.
dotenvDefault({ path: rootRelative(".env") });
dotenvLocal({ path: rootRelative(".env.local") });

export default defineConfig({
  schema: "prisma/",
  migrations: {
    path: "prisma/migrations",
  },
  datasource: {
    url: process.env["DATABASE_URL"],
    shadowDatabaseUrl: process.env["SHADOW_DATABASE_URL"],
  },
});
