// This file was generated by Prisma, and assumes you have installed the following:
// npm install --save-dev prisma dotenv
import { config as dotenvDefault } from "dotenv";
import { config as dotenvLocal } from "dotenv";
import { defineConfig } from "prisma/config";

function rootRelative(path: string): string {
  return new URL(`../../${path}`, import.meta.url).pathname;
}

// Same load order and precedence as the pre-monorepo setup.
dotenvDefault({ path: rootRelative(".env") });
dotenvLocal({ path: rootRelative(".env.local") });

function resolvePrismaUrl(): string | undefined {
  return (
    process.env.NEON_DATABASE_URL ||
    process.env.NEON_POSTGRES_PRISMA_URL ||
    process.env.NEON_POSTGRES_URL ||
    process.env.NEON_DATABASE_URL_UNPOOLED ||
    process.env.DATABASE_URL ||
    process.env.POSTGRES_URL ||
    process.env.PRISMA_DATABASE_URL
  );
}

export default defineConfig({
  schema: "prisma/",
  migrations: {
    path: "prisma/migrations",
  },
  datasource: {
    url: resolvePrismaUrl(),
    shadowDatabaseUrl: process.env.SHADOW_DATABASE_URL || process.env.NEON_DATABASE_URL_UNPOOLED,
  },
});
